# Generated by Django 5.0 on 2024-03-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScheduleManager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_class',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='subjects',
        ),
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.ManyToManyField(related_name='subjects', to='ScheduleManager.teacher'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='second_name',
            field=models.CharField(default=12, max_length=63),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(max_length=63),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=63),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=63),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=63),
        ),
    ]
