# Generated by Django 5.0 on 2024-03-10 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScheduleManager', '0002_remove_student_student_class_remove_teacher_subjects_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('classs', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='ScheduleManager.class')),
                ('subject', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='ScheduleManager.subject')),
                ('teacher', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='ScheduleManager.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ScheduleManager.student')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ScheduleManager.schedule')),
            ],
        ),
    ]
